name: CI/CD to ECS Fargate

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1
  PROJECT_NAME: ecs-fargate-demo
  ECR_REPO_NAME: ecs-fargate-proj   #  MY ECR repo name

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (with secrets)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image variables
        id: vars
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REPO="${ECR_REPO_NAME}"
          ECR_URL="$ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com/$REPO"
          IMAGE_TAG=${GITHUB_SHA::7}
          echo "ECR_URL=$ECR_URL" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "IMAGE_URI=$ECR_URL:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build and push image
        run: |
          docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
          docker tag $ECR_REPO_NAME:$IMAGE_TAG $IMAGE_URI
          docker push $IMAGE_URI


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate   
        working-directory: terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: terraform
        env:
          TF_VAR_project_name: ${{ env.PROJECT_NAME }}
          TF_VAR_aws_region:   ${{ env.AWS_REGION }}
          TF_VAR_image_uri:    ${{ env.IMAGE_URI }}
        run: terraform apply -auto-approve

      - name: Show Outputs (ALB URL)
        working-directory: terraform
        run: |
          echo "ALB DNS: $(terraform output -raw alb_dns) "
